### ISSUE TITLE
新升级的macOS Big Sur webstorm 激活失败，

### ISSUE THREAD

**Issue by unicode6674** [wenyanjun/free#3]
新升级的系统， 之前同种方法可以， 升级后就不可以啦。
方式：试用打开后，把jetbrains-agent.jar拖进去， 填入参数， 重启后，还是显示激活， 只能一直试用才能打开，坐等作者解决，

**Comment by wenyanjun** [comment]
看最新的文章 https://juejin.cn/post/7038403402690199583
